<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ServiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('services')->insert([
            [
                'id' => 'SRVC001',
                'nama' => 'Pembersihan Ruangan',
                'kalimat_promosi' => 'Melayani pembersihan ruangan mulai dari satu jam dengan pelayanan yang nyaman dan cepat.',
                'deskripsi' => "Menyapu dan mengepel lantai. Membersihkan debu di meja, lemari, jendela, dan kusen. Mengelap dinding yang dapat dijangkau. Membuang sampah dan menyegarkan udara ruangan",
                'satuan' => 'Jam',
                'harga' => 70000,
                'category_id' => 'C01',
                'gambar' => 'cleaning-1', 
                'created_at' => now(),
                'updated_at' => null,
                'status_del' => 0,
            ],
            [
                'id' => 'SRVC002',
                'nama' => 'Pembersihan Sofa',
                'kalimat_promosi' => 'Sofa kain atau kulit dibersihkan secara mendalam dengan alat vakum dan cairan khusus.',
                'deskripsi' => "Vakum menyeluruh pada seluruh permukaan sofa. Aplikasi cairan pembersih khusus sesuai bahan (kain/kulit). Pembersihan noda dan pengeringan dengan alat khusus",
                'satuan' => 'Dudukan',
                'harga' => 45000,
                'category_id' => 'C01',
                'gambar' => 'cleaning-2', 
                'created_at' => now(),
                'updated_at' => null,
                'status_del' => 0,
            ],
            [
                'id' => 'SRVC003',
                'nama' => 'Pembersihan Kasur',
                'kalimat_promosi' => 'Kasur bersih dari debu dan tungau dengan proses vakum dalam dan penyemprotan khusus.',
                'deskripsi' => "Vakum debu dan tungau dengan alat UV. Penghilangan noda menggunakan cairan khusus. Pengeringan kasur untuk mencegah kelembaban",
                'satuan' => 'Unit',
                'harga' => 70000,
                'category_id' => 'C01',
                'gambar' => 'cleaning-3', 
                'created_at' => now(),
                'updated_at' => null,
                'status_del' => 0,
            ],
            [
                'id' => 'SRVC004',
                'nama' => 'Pembersihan Kamar Mandi',
                'kalimat_promosi' => 'Membersihkan seluruh sudut kamar mandi agar kembali higienis dan bebas kerak membandel.',
                'deskripsi' => "Menyikat lantai dan dinding. Membersihkan toilet, wastafel, shower, dan cermin. Menghilangkan kerak dan lumut dengan cairan anti-jamur",
                'satuan' => 'Unit',
                'harga' => 140000,
                'category_id' => 'C01',
                'gambar' => 'cleaning-4', 
                'created_at' => now(),
                'updated_at' => null,
                'status_del' => 0,
            ],
            [
                'id' => 'SRVC005',
                'nama' => 'Pembersihan Dapur',
                'kalimat_promosi' => 'Dapur bersih dari minyak, lemak, dan kotoran dengan layanan fokus area-area penting.',
                'deskripsi' => "Membersihkan kompor, meja, backsplash, dan kitchen set. Menghilangkan lemak dan kerak membandel. Membersihkan lantai dan area sekitar dapur",
                'satuan' => 'Unit',
                'harga' => 130000,
                'category_id' => 'C01',
                'gambar' => 'cleaning-5', 
                'created_at' => now(),
                'updated_at' => null,
                'status_del' => 0,
            ],
        
            [
                'id' => 'SRVC006',
                'nama' => 'Pembersihan Kolam Renang',
                'kalimat_promosi' => 'Air kolam kembali jernih dengan perawatan menyeluruh termasuk penyaringan dan klorinasi.',
                'deskripsi' => "Menyikat dan mengangkat kotoran dari dinding, dasar dan permukaan kolam. Membersihkan skimmer dan filter air. Mengecek aliran pompa",
                'satuan' => 'Meter Persegi',
                'harga' => 20000,
                'category_id' => 'C01',
                'gambar' => 'cleaning-6', 
                'created_at' => now(),
                'updated_at' => null,
                'status_del' => 0,
            ],
            [
                'id' => 'SRVC007',
                'nama' => 'Pembersihan Taman',
                'kalimat_promosi' => 'Layanan pembersihan taman rumah agar lebih rapi, bersih, dan nyaman dipandang.',
                'deskripsi' => "Memangkas rumput dan tanaman liar. Menyapu daun dan merapikan area. Membersihkan jalur dan lantai taman",
                'satuan' => 'Meter Persegi',
                'harga' => 25000,
                'category_id' => 'C01',
                'gambar' => 'cleaning-7', 
                'created_at' => now(),
                'updated_at' => null,
                'status_del' => 0,
            ],
            [
                'id' => 'SRVC008',
                'nama' => 'Dry Cleaning Karpet',
                'kalimat_promosi' => 'Membersihkan karpet langsung di tempat tanpa perlu dicuci air, cepat dan higienis.',
                'deskripsi' => "Vakum awal untuk mengangkat debu. Penyemprotan cairan pembersih khusus. Penggosokan manual dan pengeringan dengan blower",
                'satuan' => 'Meter Persegi',
                'harga' => 50000,
                'category_id' => 'C01',
                'gambar' => 'cleaning-8', 
                'created_at' => now(),
                'updated_at' => null,
                'status_del' => 0,
            ],
            [
                'id' => 'SRVC009',
                'nama' => 'Dry Cleaning Gorden',
                'kalimat_promosi' => 'Gorden dibersihkan di tempat menggunakan metode vakum agar tetap terpasang dan bersih.',
                'deskripsi' => "Menyedot debu dan kotoran menggunakan vakum. Pembersihan menyeluruh tanpa melepas gorden. Penggunaan cairan pembersih ringan untuk noda ringan",
                'satuan' => 'Meter',
                'harga' => 35000,
                'category_id' => 'C01',
                'gambar' => 'cleaning-9', 
                'created_at' => now(),
                'updated_at' => null,
                'status_del' => 0,
            ],
            [
                'id' => 'SRVC010',
                'nama' => 'Pembersihan Bantal',
                'kalimat_promosi' => 'Bantal sofa dibersihkan langsung di rumah agar tetap segar dan bebas tungau.',
                'deskripsi' => "Vakum tungau dan debu. Pencucian luar dengan cairan anti-bakteri. Pengeringan dan pengecekan ulang",
                'satuan' => 'Pasang',
                'harga' => 40000,
                'category_id' => 'C01',
                'gambar' => 'cleaning-10', 
                'created_at' => now(),
                'updated_at' => null,
                'status_del' => 0,
            ],
            [
                'id' => 'SRVC011',
                'nama' => 'Setrika Pakaian',
                'kalimat_promosi' => 'Layanan setrika profesional untuk pakaian lebih rapi dan siap pakai di hari yang sama.',
                'deskripsi' => "Setrika dengan suhu sesuai bahan kain. Pelipatan rapi dan bersih",
                'satuan' => 'Jam',
                'harga' => 50000,
                'category_id' => 'C02',
                'gambar' => 'laundry-1', 
                'created_at' => now(),
                'updated_at' => null,
                'status_del' => 0,
            ],
            [
                'id' => 'SRVC012',
                'nama' => 'Pembersihan Tas Kain & Ransel',
                'kalimat_promosi' => 'Tas dan ransel kembali bersih dan wangi dengan metode deep clean khusus.',
                'deskripsi' => "Membersihkan bagian luar dan dalam tas. Penyikatan tali dan resleting. Pengeringan dengan blower",
                'satuan' => 'Unit',
                'harga' => 40000,
                'category_id' => 'C02',
                'gambar' => 'laundry-2', 
                'created_at' => now(),
                'updated_at' => null,
                'status_del' => 0,
            ],
            [
                'id' => 'SRVC013',
                'nama' => 'Cuci Sepatu',
                'kalimat_promosi' => 'Sepatu bersih, wangi, dan awet! Layanan cuci sepatu profesional dengan teknik aman untuk semua jenis bahan (kulit, kain, sintetis).',
                'deskripsi' => "Pembersihan bagian luar dan dalam sepatu. Penghilangan noda dengan cairan khusus sesuai bahan (kulit, kain, sintetis). Pengeringan terkontrol menggunakan alat blower bertekanan rendah dan pengharum anti-bakteri",
                'satuan' => 'Pasang',
                'harga' => 55000,
                'category_id' => 'C02',
                'gambar' => 'laundry-3', 
                'created_at' => now(),
                'updated_at' => null,
                'status_del' => 0,
            ],
            [
                'id' => 'SRVC014',
                'nama' => 'Cuci Boneka',
                'kalimat_promosi' => 'Bersihkan boneka kesayangan dari debu dan tungau dengan metode hypoallergenic.',
                'deskripsi' => "Vakum debu dan tungau di permukaan boneka. Pencucian manual dengan deterjen lembut dan anti-alergi. Pengeringan cepat untuk mencegah kerusakan bahan",
                'satuan' => 'Unit',
                'harga' => 40000,
                'category_id' => 'C02',
                'gambar' => 'laundry-4', 
                'created_at' => now(),
                'updated_at' => null,
                'status_del' => 0,
            ],
            [
                'id' => 'SRVC015',
                'nama' => 'Cuci AC',
                'kalimat_promosi' => 'AC lebih dingin dan hemat listrik setelah dibersihkan bagian dalam dan luar secara tuntas.',
                'deskripsi' => "Membersihkan filter, kipas, dan evaporator. Cuci casing AC bagian luar. Pengecekan kebocoran dan aliran air",
                'satuan' => 'Unit',
                'harga' => 90000,
                'category_id' => 'C03',
                'gambar' => 'maintenance-1', 
                'created_at' => now(),
                'updated_at' => null,
                'status_del' => 0,
            ],
            [
                'id' => 'SRVC016',
                'nama' => 'Perbaikan Pipa Rumah Tangga',
                'kalimat_promosi' => 'Tangani kebocoran, mampet, dan gangguan saluran air rumah Anda dengan cepat dan rapi.',
                'deskripsi' => "Perbaikan bocor ringan pada pipa atau kran. Pembersihan saluran mampet (wastafel/floor drain). Penggantian seal atau pipa pendek",
                'satuan' => 'Jam',
                'harga' => 100000,
                'category_id' => 'C03',
                'gambar' => 'maintenance-2',                
                'created_at' => now(),
                'updated_at' => null,
                'status_del' => 0,
            ],
            [
                'id' => 'SRVC017',
                'nama' => 'Perbaikan Listrik Rumahan',
                'kalimat_promosi' => 'Tangani masalah listrik rumah seperti stop kontak rusak, lampu mati, atau korsleting.',
                'deskripsi' => "Pengecekan jalur listrik dan penggantian komponen rusak. Perbaikan saklar, stop kontak, atau instalasi dasar. Penggunaan alat pengaman standar",
                'satuan' => 'Jam',
                'harga' => 140000,
                'category_id' => 'C03',
                'gambar' => 'maintenance-3', 
                'created_at' => now(),
                'updated_at' => null,
                'status_del' => 0,
            ],
            [
                'id' => 'SRVC018',
                'nama' => 'Perakitan Furniture',
                'kalimat_promosi' => 'Bantu rakitan furniture baru seperti meja, kursi, lemari dengan cepat dan rapi.',
                'deskripsi' => "Perakitan sesuai petunjuk manual. Pemasangan aksesori (engsel, roda, pegangan). Penyesuaian posisi dan pengecekan kestabilan",
                'satuan' => 'Unit',
                'harga' => 45000,
                'category_id' => 'C03',
                'gambar' => 'maintenance-4',                
                'created_at' => now(),
                'updated_at' => null,
                'status_del' => 0,
            ],
            [
                'id' => 'SRVC019',
                'nama' => 'Disinfeksi Ruangan',
                'kalimat_promosi' => 'Ruangan disemprot disinfektan menyeluruh untuk membasmi virus dan bakteri penyebab penyakit.',
                'deskripsi' => "Penyemprotan disinfektan food-grade ke seluruh permukaan. Fokus pada area sentuhan tinggi (gagang pintu, meja, kursi). Membunuh virus, bakteri, dan jamur",
                'satuan' => 'Meter Persegi',
                'harga' => 35000,
                'category_id' => 'C04',
                'gambar' => 'disinfection-1',
                'created_at' => now(),
                'updated_at' => null,
                'status_del' => 0,
            ],
            [
                'id' => 'SRVC020',
                'nama' => 'Fogging Serangga',
                'kalimat_promosi' => 'Layanan fogging efektif membasmi nyamuk, kecoa, dan serangga lainnya sampai ke sarangnya.',
                'deskripsi' => "Pengasapan area dalam dan luar rumah. Target nyamuk, kecoa, dan serangga kecil lainnya. Cocok untuk pencegahan demam berdarah",
                'satuan' => 'Meter Persegi',
                'harga' => 25000,
                'category_id' => 'C04',
                'gambar' => 'disinfection-2',
                'created_at' => now(),
                'updated_at' => null,
                'status_del' => 0,
            ],
            [
                'id' => 'SRVC021',
                'nama' => 'Disinfeksi Tangki Air',
                'kalimat_promosi' => 'Ruangan disemprot disinfektan menyeluruh untuk membasmi virus dan bakteri penyebab penyakit.',
                'deskripsi' => "Pengurasan tangki dan penghilangan kerak/lumut. Penyemprotan disinfektan khusus tangki air. Pengecekan kebersihan sebelum pengisian ulang",
                'satuan' => 'Unit',
                'harga' => 120000,
                'category_id' => 'C04',
                'gambar' => 'disinfection-3',
                'created_at' => now(),
                'updated_at' => null,
                'status_del' => 0,
            ],
            [
                'id' => 'SRVC022',
                'nama' => 'Disinfeksi Mobil',
                'kalimat_promosi' => 'Layanan fogging efektif membasmi nyamuk, kecoa, dan serangga lainnya sampai ke sarangnya.',
                'deskripsi' => "Penyemprotan disinfektan food-grade pada dashboard, jok, dan pegangan. Fokus pada area sentuhan tinggi (stir, tombol, pintu). Aman untuk bahan kulit dan elektronik",
                'satuan' => 'Unit',
                'harga' => 100000,
                'category_id' => 'C04',
                'gambar' => 'disinfection-4',
                'created_at' => now(),
                'updated_at' => null,
                'status_del' => 0,
            ]
        ]);
    }
}
